DROP TABLE IF EXISTS data;
CREATE TABLE data (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  w1 FLOAT(10) NOT NULL,
  x FLOAT(10) NOT NULL,
  w2 FLOAT(10) NOT NULL,
  PRIMARY KEY (id));